# Generated by Django 3.0.8 on 2020-07-23 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
